# Generated by Django 5.2.8 on 2025-12-20 15:34

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('pages', django.db.models.manager.Manager()),
            ],
        ),
    ]
