# Generated by Django 6.0 on 2025-12-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='name',
            new_name='student',
        ),
    ]
